- project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
> [Feat] 입찰 등록 기능 구현 (#1)

- project/src/main/java/org/example/fourtreesproject/gpbuy/controller/GpbuyController.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Category.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Groupbuy.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/model/entity/Likes.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/model/request/GpbuyCreateRequest.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/repository/GpbuyRepository.java
- project/src/main/java/org/example/fourtreesproject/gpbuy/service/GpbuyService.java
등록 기능을 위한 엔티티 선 개발
양방향 연관관계
- 카테고리
- 공구
- 관심공구
> [Feat] 공구 등록 기능 엔티티(카테고리, 공구, 관심공구) 개발 (#4)

- project/src/main/java/org/example/fourtreesproject/config/JwtFilter.java
- project/src/main/java/org/example/fourtreesproject/emailVerify/model/entity/EmailVerify.java
- project/src/main/java/org/example/fourtreesproject/jwt/Repository/RefreshTokenRepository.java
- project/src/main/java/org/example/fourtreesproject/jwt/model/entity/RefreshToken.java
- project/src/main/java/org/example/fourtreesproject/oauth/OAuth2AuthenticationSuccessHandler.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
User, RefreshToken, EmailVerify Entity에 @Table 어노테이션 추가
> [Refactor] 회원Entity, RefreshToken Entity, EmailVerify Entity 수정

- project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
- project/src/main/java/org/example/fourtreesproject/company/repository/CompanyRepository.java
- project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
- project/src/main/java/org/example/fourtreesproject/product/model/entity/Product.java
- project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
- project/src/main/java/org/example/fourtreesproject/product/repository/ProductImgRepository.java
- project/src/main/java/org/example/fourtreesproject/product/repository/ProductRepository.java
상품, 상품이미지, 업체 엔티티&레포지토리 생성했습니다.
> [Feat] 상품, 상품이미지, 업체 엔티티 생성

- project/src/main/java/org/example/fourtreesproject/delivery/model/DeliveryAddress.java
- project/src/main/java/org/example/fourtreesproject/delivery/repository/DeliveryAddressRepository.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
> [Feat] DeliveryAddress Entity 생성 및 User 연관관계 맺기 (#9)

- project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
- project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
> [Bug] Jpa 연관관계 잘못 설정한 걸로 인한 버그 수정

- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/RegisteredBidListResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Feat] 등록된 입찰 조회 구현중 (#31)

- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Feat] 등록된 입찰 조회 기능 구현 (#31)

- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Fix] 정렬 순서 오류 수정 (#39)

- project/src/main/java/org/example/fourtreesproject/config/JwtFilter.java
- project/src/main/java/org/example/fourtreesproject/delivery/model/DeliveryAddress.java
- project/src/main/java/org/example/fourtreesproject/delivery/model/request/DeliveryAddressRegisterRequest.java
- project/src/main/java/org/example/fourtreesproject/delivery/repository/DeliveryAddressRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
- project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
> [Feat] 배송지 추가 api 구현 (#9)

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
GroupBuyController에 registerdBidList주석 해제
> [Fix] GroupBuyController에 registerdBidList주석 해제

- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
- project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
Orders Entity 개발
User Entity에 연관관계 추가
GroupBut Entity에 연관관계 추가
> [Feat] 주문 Entity 개발 완료 (#46)

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Feat] 공구 시작 기능 구현 (#41)

- project/src/main/java/org/example/fourtreesproject/coupon/controller/CouponController.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/Coupon.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/UserCoupon.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/request/CouponRegisterRequest.java
- project/src/main/java/org/example/fourtreesproject/coupon/repository/CouponRepository.java
- project/src/main/java/org/example/fourtreesproject/coupon/service/CouponService.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
- project/src/main/java/org/example/fourtreesproject/user/model/response/UserInfoResponse.java
> [Feat] 쿠폰 등록 기능 구현

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/model/response/BidMyListResponse.java
- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
> [Feat] 입찰 현황 조회 기능 예외 처리 전 (#5)

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyListResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/GroupBuyRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
page, size 넘겨받아 슬라이싱 처리해서 전체 공구 조회
> [Feat] 공구 전체 조회 기능 구현 (#49)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
- project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
- project/src/main/java/org/example/fourtreesproject/company/model/request/CompanyModifyRequest.java
- project/src/main/java/org/example/fourtreesproject/company/repository/CompanyRepository.java
- project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
> [Feat] 업체 정보 수정 기능 구현 (#20)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
CompanyController - /detail 부분 괄호 오류 있어서 수정 했습니다.
> [Fix] 업체 정보 조회 에러 수정

- project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/SellerDetail.java
- project/src/main/java/org/example/fourtreesproject/user/model/response/SellerInfoResponse.java
- project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
> [Feat] 업체 회원 상세 정보 조회 구현 (#57)

- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyListResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Fix] GroupBuy Entity에 컬럼 추가 (#58)

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyDetailResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
> [Feat] 공구 상세조회 기능 구현 (#63)

- project/build.gradle
- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/model/response/GpbuyWaitListResponse.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/GroupBuyRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDsl.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDslImpl.java
> [Feat] 입찰 대기 공구 조회 기능 예외 처리 전 (#15)

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/User.java
> [Feat] 관심 공구 등록/취소 기능 구현

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
- project/src/main/java/org/example/fourtreesproject/bid/model/request/BidModifyRequest.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
> [Feat] 입찰 수정 기능 예외 처리 전 (#13)

- project/build.gradle
- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/exception/customs/GroupBuyRegisterFailException.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyLikesListResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Feat] 관심공구 조회기능 구현 (#70)

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
- project/src/main/java/org/example/fourtreesproject/bid/model/request/BidCancelRequest.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
> [Feat] 입찰 취소 기능 예외 처리 전 (#14)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
- project/src/main/java/org/example/fourtreesproject/company/model/entity/Company.java
- project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
- project/src/main/java/org/example/fourtreesproject/config/S3Config.java
- project/src/main/java/org/example/fourtreesproject/file/CloudFileUploadService.java
- project/src/main/java/org/example/fourtreesproject/file/FileUploadService.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Category.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/CategoryRepository.java
- project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
- project/src/main/java/org/example/fourtreesproject/product/model/entity/Product.java
- project/src/main/java/org/example/fourtreesproject/product/model/entity/ProductImg.java
- project/src/main/java/org/example/fourtreesproject/product/model/request/ProductRegisterRequest.java
- project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
> [Feat] 상품 등록 기능 구현 (#6)

- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/querydsl/GroupBuyRepositoryDslImpl.java
> [Fix] 조회 조건 오입력 수정

- project/src/main/java/org/example/fourtreesproject/bid/model/entity/Bid.java
- project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
- project/src/main/java/org/example/fourtreesproject/config/PortoneConfig.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/Coupon.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/UserCoupon.java
- project/src/main/java/org/example/fourtreesproject/coupon/repository/UserCouponRepository.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
- project/src/main/java/org/example/fourtreesproject/orders/exception/OrderExceptionHandler.java
- project/src/main/java/org/example/fourtreesproject/orders/exception/custom/InvalidOrderException.java
- project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
- project/src/main/java/org/example/fourtreesproject/orders/model/request/OrderRequest.java
- project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
- project/src/main/java/org/example/fourtreesproject/user/model/entity/UserDetail.java
> [Feat] 주문, 공구 시작, 공구 참여, 입찰 선정 기능 구현

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/Likes.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [Refactor]공구 기능의 유저정보를 시큐리티 컨텍스트에서 받아오도록 리팩토링 (#87)

- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
- project/src/main/java/org/example/fourtreesproject/orders/model/response/OrderPageResponse.java
- project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
- project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
- project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
- project/src/main/java/org/example/fourtreesproject/user/model/response/UserCouponResponse.java
주문 페이지에서 사용할 회원 정보, 배송지 정보, 쿠폰 정보, 포인트를 반환한다.
> [Feat] 주문 페이지 조회 기능 구현

- project/src/main/java/org/example/fourtreesproject/bid/repository/BidRepository.java
- project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
- project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
- project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
- project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
> [Feat] 주문 내역 조회 구현 (#83)

- project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
- project/src/main/java/org/example/fourtreesproject/product/model/response/ProductCategoryResponse.java
- project/src/main/java/org/example/fourtreesproject/product/model/response/ProductImgResponse.java
- project/src/main/java/org/example/fourtreesproject/product/model/response/ProductMylistResponse.java
- project/src/main/java/org/example/fourtreesproject/product/repository/ProductImgRepository.java
- project/src/main/java/org/example/fourtreesproject/product/repository/ProductRepository.java
- project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
> [Feat] 등록 상품 조회 기능 구현 (#25)

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/exception/BidExceptionHandler.java
- project/src/main/java/org/example/fourtreesproject/bid/exception/customs/InvalidBidException.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
- project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
입찰 등록, 수정, 삭제,
입찰 대기 공구 조회,
입찰 현황 조회
> [Fix] 입찰 기능 예외 처리 (#94)

- project/src/main/java/org/example/fourtreesproject/config/SwaggerConfig.java
- project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
swagger페이지에서 Authorization 헤더 추가 가능하도록 config 파일 수정
> [Docs] OrderController에 swagger 설정 및 swagger config 수정

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
- project/src/main/java/org/example/fourtreesproject/company/model/request/CompanyModifyRequest.java
- project/src/main/java/org/example/fourtreesproject/file/CloudFileUploadService.java
- project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
ProductController, CompanyControllerd의 ROLE_USER 권한 수정
> [Fix] 업체기능 권한설정 코드 수정

- project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
> [Docs] ProductController swagger 설정 (#99)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
> [Docs] CompanyController swagger 설정(#99)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
> [fix] swagger 에러

- project/src/main/java/org/example/fourtreesproject/groupbuy/model/entity/GroupBuy.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/repository/LikesRepository.java
20개 가까이 -> 5개까지 개선
fetch join과 batch size활용
> [Refactor] 관심 공구 조회 쿼리빈도 개선 (#121)

- project/src/main/java/org/example/fourtreesproject/aop/MethodExecutionTimer.java
- project/src/main/java/org/example/fourtreesproject/common/annotation/Timer.java
- project/src/main/java/org/example/fourtreesproject/orders/model/entity/Orders.java
- project/src/main/java/org/example/fourtreesproject/orders/model/response/OrdersListResponse.java
- project/src/main/java/org/example/fourtreesproject/orders/repository/OrdersRepository.java
- project/src/main/java/org/example/fourtreesproject/orders/service/OrdersService.java
> [Perf] 주문 내역 조회 성능 개선

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
> [fix] bid swagger 수정

- project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
- project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
> [Fix] 중복 이메일 회원 가입 불가능 하게 설정

- project/src/main/java/org/example/fourtreesproject/user/repository/UserRepository.java
> [Fix] coupon이 없는 일반 회원 정보 조회시 오류 fix (#130)

- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCompanyException.java
- project/src/main/java/org/example/fourtreesproject/product/service/ProductService.java
상품 찾을 때 company의 Idx로 찾아야되는데 user의 Idx로 찾던 버그 수정
> [Fix] 상품 조회 버그 수정

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
- project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
- project/src/main/java/org/example/fourtreesproject/exception/GlobalExceptionHandler.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/GroupBuyRegisterFailException.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidBidException.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCompanyException.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidCustomException.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidOrderException.java
- project/src/main/java/org/example/fourtreesproject/exception/custom/InvalidUserException.java
> [Fix] 업체 중복 등록 버그 해결, 예외 처리 버그 해결 (#138)

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
> [Fix] swagger 업체 기본값 설정

- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/orders/controller/OrdersController.java
- project/src/main/java/org/example/fourtreesproject/product/controller/ProductController.java
- project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
swagger 상품, 결제 코멘트 설정 (상품 등록 api 기본값 설정 시 에러나서 아직 미완성)
> [Fix] swagger 상품, 결제  기본값, 코멘트 설정

- project/src/main/java/org/example/fourtreesproject/common/BaseResponse.java
- project/src/main/java/org/example/fourtreesproject/common/BaseResponseStatus.java
- project/src/main/java/org/example/fourtreesproject/config/LoginFilter.java
- project/src/main/java/org/example/fourtreesproject/config/SecurityConfig.java
- project/src/main/java/org/example/fourtreesproject/exception/CustomAccessDeniedHandler.java
- project/src/main/java/org/example/fourtreesproject/exception/CustomAuthenticationEntryPoint.java
> [Feat] security 접근 권한 설정

- project/src/main/java/org/example/fourtreesproject/delivery/model/response/DeliveryAddressRegisterResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/controller/GroupBuyController.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/request/GroupBuyCreateRequest.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/model/response/GroupBuyRegisterResponse.java
- project/src/main/java/org/example/fourtreesproject/groupbuy/service/GroupBuyService.java
- project/src/main/java/org/example/fourtreesproject/user/controller/UserController.java
- project/src/main/java/org/example/fourtreesproject/user/service/UserService.java
> [Feat] 배송지 등록, 공구 등록 시 idx값 반환

- project/src/main/java/org/example/fourtreesproject/bid/controller/BidController.java
- project/src/main/java/org/example/fourtreesproject/bid/model/response/BidRegisterResponse.java
- project/src/main/java/org/example/fourtreesproject/bid/service/BidService.java
- project/src/main/java/org/example/fourtreesproject/coupon/controller/CouponController.java
- project/src/main/java/org/example/fourtreesproject/coupon/model/response/CouponRegisterResponse.java
- project/src/main/java/org/example/fourtreesproject/coupon/service/CouponService.java
입찰등록 bidIdx, 쿠폰등록 couponIdx 반환
> [Fix] 입찰 등록, 쿠폰 등록 response 수정 (#170)

- project/src/main/java/org/example/fourtreesproject/company/controller/CompanyController.java
- project/src/main/java/org/example/fourtreesproject/company/model/response/CompanyRegisterResponse.java
- project/src/main/java/org/example/fourtreesproject/company/service/CompanyService.java
업체 등록 Response 추가 => 업체 등록시 업체 idx 반환
> [Fix] 업체 등록 Response 수정
